#!/usr/bin/env python3
"""
crm_sync.py — the supported way to get CRM data into a registry, and to find out when
the two have drifted apart.

Every skill in this system says it can "import from a CRM". Until this existed, none of
them shipped an implementation, so each session improvised one — and an improvised
importer is almost always a *seeder* that gets re-run later as though it were a
*refresh*. That rebuilds every row from a stale snapshot, silently reverting whatever
happened in between, and the result validates perfectly clean afterwards because it is
clean. It's just wrong.

Hence three verbs that mean different things and refuse to be each other:

  --seed     First load only. Refuses to run against a registry that already has rows.
  --refresh  Field-level merge. Touches only columns the schema marks owner "crm";
             local and derived columns survive untouched. Never renumbers an id.
  --verify   Read-only. Reports drift in both directions and changes nothing.

Plus an ingest path for bulk data, because pulling 27,000 leads through a connector one
record at a time is not a plan:

  --ingest   Read a CRM report export (CSV/TSV) and feed it through --seed or --refresh.

The CRM read itself lives in the skill, not here. The CRM is reachable only through a
connector the agent holds, so the agent fetches and hands the result over as JSON:

    crm_sync.py --plan <project> --registry opportunities      # what to select
    ... agent runs the query through the CRM connector, writes snapshot.json ...
    crm_sync.py --verify <project> --registry opportunities --json-file snapshot.json

Usage:
  crm_sync.py --plan    <project> [--registry NAME]
  crm_sync.py --seed    <project> --registry NAME --json-file recs.json
  crm_sync.py --refresh <project> --registry NAME --json-file recs.json [--dry-run]
  crm_sync.py --verify  <project> --registry NAME --json-file snapshot.json
  crm_sync.py --ingest  <project> --registry NAME [--file export.csv] [--mode refresh]

Exit codes: 0 fine, 1 needs a human, 2 usage error.
"""

import argparse
import csv
import io
import json
import os
import re
import sys
from datetime import datetime, date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import csvguard as G


# ------------------------------------------------------------------ report exports
# Report exports fail in the same handful of ways whatever the CRM, because the failures
# come from the export machinery — Windows encodings, locale date formats, spreadsheet
# conventions — rather than from the vendor. So the handling here is generic by default.
#
# Where something genuinely is vendor-specific (Salesforce's __c suffixes and managed
# package namespaces, its 15/18-character IDs), it's declared in csvguard's CRM_DIALECTS
# and applied only when the profile says that's the CRM. Nothing below fires for a CRM
# that hasn't declared it.

ENCODINGS = ["utf-8-sig", "cp1252", "latin-1"]

FOOTER_PAT = re.compile(
    r"^(grand totals?|totals?|subtotals?|confidential information|generated by|"
    r"copyright|report generated|\d+ records?)\b", re.IGNORECASE)


def read_export(path):
    """Read a report export without dying on the first accented name.

    Anything exported through a Windows toolchain tends to be cp1252 rather than UTF-8,
    and a plain open() raises UnicodeDecodeError on the first 'Müller' or curly
    apostrophe, several thousand rows in. Try the likely encodings in order rather than
    assuming — this is not specific to any one CRM."""
    raw = open(path, "rb").read()
    text, used = None, None
    for enc in ENCODINGS:
        try:
            text = raw.decode(enc)
            used = enc
            break
        except UnicodeDecodeError:
            continue
    if text is None:
        text = raw.decode("utf-8", errors="replace")
        used = "utf-8 (with replacements — some characters were unreadable)"

    delim = "\t" if path.lower().endswith((".tsv", ".tab")) else None
    if delim is None:
        sample = text[:8000]
        delim = "\t" if sample.count("\t") > sample.count(",") else ","
    rows = list(csv.reader(io.StringIO(text), delimiter=delim))
    return rows, used, delim


def find_header(rows, known):
    """Report exports often carry a title row, a filter summary and a blank line above
    the real header. Pick the row that looks most like column names."""
    best, best_score = 0, -1
    for i, r in enumerate(rows[:15]):
        cells = [c.strip() for c in r if c and c.strip()]
        if len(cells) < 2:
            continue
        score = sum(1 for c in cells if norm_label(c) in known) * 10 + len(cells)
        if score > best_score:
            best, best_score = i, score
    return best


def strip_footers(rows, ncols):
    """Drop 'Grand Totals', the confidentiality line, and the blank rows around them.
    A totals row read as data becomes a phantom record with a real-looking amount."""
    out, dropped = [], []
    for r in rows:
        cells = [(c or "").strip() for c in r]
        if not any(cells):
            continue
        first = cells[0]
        filled = sum(1 for c in cells if c)
        if FOOTER_PAT.match(first) or (filled <= 2 and ncols > 4 and not first):
            dropped.append(" | ".join(c for c in cells if c)[:80])
            continue
        out.append(r)
    return out, dropped


def norm_label(s, dialect=None):
    """'Lead Status', 'Lead_Status__c', 'status' all collapse to the same thing.

    Stripping punctuation and case is generic. Stripping a custom-field suffix is not —
    it only happens for a CRM whose dialect declares one, so a CRM with a field genuinely
    named `foo__c` isn't quietly renamed."""
    s = (s or "").strip()
    suffix = (dialect if dialect is not None else G._DIALECT).get("field_suffix")
    if suffix and s.lower().endswith(suffix.lower()):
        s = s[: -len(suffix)]
    s = re.sub(r"[^0-9a-zA-Z]+", " ", s).strip().lower()
    return re.sub(r"\s+", "", s)


OBJECT_WORDS = ("lead", "opportunity", "account", "contact", "case", "partner",
                "customer", "deal", "record")


def label_variants(n):
    """A report label and an API name describe the same field in different dialects.
    'Lead Status' is 'Status'; 'Last Activity' is 'LastActivityDate'; 'Active Lead' is
    'SalesLoft1__Active_Lead__c'. Try the handful of transformations that account for
    nearly all of it, rather than fuzzy-matching and importing the wrong column."""
    seen = [n]
    for w in OBJECT_WORDS:
        if n.startswith(w) and len(n) > len(w) + 2:
            seen.append(n[len(w):])
        if n.endswith(w) and len(n) > len(w) + 2:
            seen.append(n[:-len(w)])
    for base in list(seen):
        if base.endswith("date"):
            seen.append(base[:-4])
        else:
            seen.append(base + "date")
        if not base.endswith("name"):
            seen.append(base + "name")
    out = []
    for v in seen:
        if v and v not in out:
            out.append(v)
    return out


def build_label_map(root, registry, schema, extra=None):
    """CSV header -> local column name.

    Exports carry field *labels* ('Lead Status'); the profile maps local names to API
    names ('Status'). Both have to resolve, plus whatever the user overrides."""
    fm = G.load_field_map(root)
    d = G.set_dialect(fm)
    fields = ((fm.get("objects", {}) or {}).get(registry, {}) or {}).get("fields", {})
    m = {}
    for c in schema["columns"]:
        m[norm_label(c["name"], d)] = c["name"]
    for local, api in fields.items():
        m[norm_label(api, d)] = local
        m[norm_label(local, d)] = local
        # Some CRMs let managed packages namespace their fields
        # (SalesLoft1__Active_Lead__c under Salesforce); the report label drops the
        # namespace, so register the bare form too. Only for a CRM that declares one.
        sep = d.get("namespace_separator")
        if sep and sep in api:
            m.setdefault(norm_label(api.split(sep, 1)[1], d), local)
    # Export labels that no field map covers, because they name the record rather than a
    # field on it. All of these are conventions of report writers generally, not of any
    # one CRM — and each is registered with setdefault, so a real mapping always wins.
    generic = [("recordid", "crm_id"), ("id", "crm_id"), ("objectid", "crm_id"),
               ("lastmodifieddate", "crm_last_modified"),
               ("lastmodified", "crm_last_modified"),
               ("modified", "crm_last_modified"), ("updatedat", "crm_last_modified"),
               ("dateupdated", "crm_last_modified"), ("datemodified", "crm_last_modified"),
               ("createddate", "created_date"), ("createdat", "created_date"),
               ("dateadded", "created_date"), ("ownerfullname", "owner"),
               ("accountname", "account_name"), ("companyname", "company")]
    # "<Object> ID" / "<Object> Owner" / "<Object> Name" is how most exports label the
    # record's own columns, so derive them from the object's name instead of listing
    # every vendor's nouns.
    obj = norm_label((fm.get("objects", {}) or {}).get(registry, {})
                     .get("crm_object", "") or "", d)
    for word in {obj} | set(OBJECT_WORDS):
        if not word:
            continue
        generic += [(f"{word}id", "crm_id"), (f"{word}owner", "owner"),
                    (f"{word}name", "name")]
    for alias in (d.get("id_aliases") or []) + [d.get("id_field")]:
        if alias:
            generic.append((norm_label(alias, d), "crm_id"))
    for label, local in generic:
        m.setdefault(label, local)
    names = {c["name"] for c in schema["columns"]}
    saved = os.path.join(root, G.PROFILE_DIR, f"import-map-{registry}.json")
    if os.path.exists(saved):
        try:
            with open(saved, encoding="utf-8") as f:
                for k, v in json.load(f).items():
                    m[norm_label(k)] = v
        except (json.JSONDecodeError, OSError):
            pass
    for k, v in (extra or {}).items():
        m[norm_label(k)] = v
    return {k: v for k, v in m.items() if v in names}


def coerce(value, col):
    """Normalise one exported cell to the canonical form the registry stores.

    Export data is inconsistent in ways a person wouldn't notice: US-locale M/D/YYYY
    dates, currency symbols and thousands separators, and booleans that arrive as 0/1
    in one column, true/false in another and blank-for-false in a third."""
    v = (value or "").strip()
    if not v:
        return ""
    t = (col or {}).get("type", "text")
    if t == "date":
        return G.norm_date(v)[0]
    if t == "money":
        return G.norm_money(v)[0]
    if t == "number":
        return G.norm_number(v)[0]
    if t == "bool":
        return G.norm_bool(v)[0]
    if t == "enum":
        out, _, ok = G.norm_enum(v, col.get("values", []))
        return out
    return G.norm_text(v)[0]


def ingest(root, registry, path, extra_map=None, key="crm_id"):
    """Turn a report export into records ready for --seed or --refresh."""
    schema = G.schema_by_registry(root, registry)
    spec = {c["name"]: c for c in schema["columns"]}
    rows, encoding, delim = read_export(path)
    if not rows:
        raise SystemExit(f"error: {os.path.basename(path)} is empty")

    lookup = build_label_map(root, registry, schema, extra_map)
    hi = find_header(rows, set(lookup))
    header = [c.strip() for c in rows[hi]]
    body, dropped = strip_footers(rows[hi + 1:], len(header))

    mapped, unmapped, guessed = {}, [], []
    for i, h in enumerate(header):
        if not h:
            continue
        local, exact = None, True
        for j, v in enumerate(label_variants(norm_label(h, G._DIALECT))):
            if v in lookup:
                local, exact = lookup[v], (j == 0)
                break
        if local and local in mapped.values():
            continue                  # a second column claiming the same field
        if local:
            mapped[i] = local
            if not exact:
                guessed.append(f"{h} -> {local}")
        else:
            unmapped.append(h)

    records, blank_key = [], 0
    for r in body:
        rec = {}
        for i, local in mapped.items():
            if i < len(r):
                val = coerce(r[i], spec.get(local))
                if val != "":
                    rec[local] = val
        if not rec.get(key):
            blank_key += 1
            continue
        records.append(rec)

    return {"records": records, "encoding": encoding, "delimiter": delim,
            "header_row": hi + 1, "columns_mapped": sorted(set(mapped.values())),
            "unmapped": unmapped, "guessed": guessed, "footers_dropped": dropped,
            "rows_read": len(body), "blank_key": blank_key}


# ------------------------------------------------------------------------ sync log


def log_sync(root, direction, obj, outcome, detail, fields=""):
    """CONVENTIONS §7: log everything, pulls included."""
    try:
        schema = G.load_schemas(root).get("sync_log")
        if not schema:
            return
        path = G.resolve_path(os.path.join(root, schema["path"]), root)
        if not os.path.exists(path):
            G.write_table(path, [c["name"] for c in schema["columns"]], [],
                          schema=schema, root=root, guard=False)
        header, rows = G.read_table(path, schema)
        idx = {h: i for i, h in enumerate(header)}
        used = {r[idx["id"]] for r in rows if idx["id"] < len(r) and r[idx["id"]]}
        rec = {"id": f"SYNC-{G.next_free(used, 'SYNC', 6):06d}",
               "timestamp": datetime.now().isoformat(timespec="seconds"),
               "direction": direction, "object": obj, "outcome": outcome,
               "fields_changed": fields, "detail": detail[:500]}
        rows.append([rec.get(h, "") for h in header])
        G.write_table(path, header, rows, schema=schema, root=root, guard=False)
    except Exception as e:                                  # never fail a sync on its log
        print(f"warning: couldn't write the sync log ({e})", file=sys.stderr)


# --------------------------------------------------------------------------- verbs


def registry_path(root, schema):
    return G.resolve_path(os.path.join(root, schema["path"]), root)


def row_count(path, schema):
    if not os.path.exists(path):
        return 0
    try:
        return len(G.read_table(path, schema)[1])
    except Exception:
        return 0


def do_seed(root, registry, records, force=False, source=""):
    schema = G.schema_by_registry(root, registry)
    path = registry_path(root, schema)
    n = row_count(path, schema)
    if n and not force:
        print(f"REFUSING TO SEED {os.path.basename(path)} — it already holds {n} rows.\n")
        print("  --seed builds a registry from scratch. Run against a live one it would")
        print("  rebuild every row from this snapshot, reverting anything changed since")
        print("  it was taken — and the result would validate clean, because it would be.")
        print(f"\n  You almost certainly want:")
        print(f"    crm_sync.py --refresh {root} --registry {registry} --json-file ...")
        print(f"  which merges CRM-owned fields and leaves local ones alone.")
        print(f"\n  If you really do mean to rebuild it, pass --force.")
        return 1
    u, i, sk, changes = G.upsert(path, schema, records, key="crm_id", root=root,
                                 only_owner=None, force=force)
    print(f"seeded {registry}: {i} rows created, {u} updated"
          + (f", {sk} skipped with no crm_id" if sk else ""))
    log_sync(root, "pull", registry, "ok",
             f"seed{' from ' + source if source else ''}: {i} created, {u} updated")
    return 0


def do_refresh(root, registry, records, dry_run=False, force=False, source=""):
    schema = G.schema_by_registry(root, registry)
    path = registry_path(root, schema)
    if not os.path.exists(path):
        print(f"{os.path.basename(path)} doesn't exist yet — use --seed for a first load.")
        return 1

    local_cols = [c["name"] for c in schema["columns"]
                  if G.column_owner(c) in ("local", "derived")]
    if dry_run:
        # Show what would change without touching anything: run the same comparison
        # verify uses, since a refresh is exactly "accept every DRIFT".
        print(f"dry run — {registry}: {len(records)} incoming records")
        return G.verify_sync(root, registry, records)

    u, i, sk, changes = G.upsert(path, schema, records, key="crm_id", root=root,
                                 only_owner=["crm"], force=force)
    print(f"refreshed {registry}: {u} rows updated, {i} new, "
          f"{max(0, len(records) - u - i - sk)} already current"
          + (f", {sk} skipped with no crm_id" if sk else ""))
    for c in changes[:25]:
        print(f"  {c}")
    if len(changes) > 25:
        print(f"  ... and {len(changes) - 25} more")
    print(f"\n  Untouched, as always on a refresh: {', '.join(local_cols[:8])}"
          + (f" and {len(local_cols) - 8} more local columns" if len(local_cols) > 8 else ""))
    log_sync(root, "pull", registry, "ok",
             f"refresh{' from ' + source if source else ''}: {u} updated, {i} new")
    return 0


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--plan")
    ap.add_argument("--seed")
    ap.add_argument("--refresh")
    ap.add_argument("--verify")
    ap.add_argument("--ingest")
    ap.add_argument("--registry")
    ap.add_argument("--json")
    ap.add_argument("--json-file", dest="json_file")
    ap.add_argument("--file", help="Report export to ingest (default: newest in "
                                   "<module>/import/)")
    ap.add_argument("--mode", choices=["seed", "refresh", "records"], default="refresh",
                    help="What --ingest does with what it read")
    ap.add_argument("--map", help="JSON of {csv header: local column} for columns the "
                                  "profile doesn't cover")
    ap.add_argument("--key", default="crm_id")
    ap.add_argument("--out", help="Write the ingested records to this JSON file")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args()

    root = os.path.abspath(a.plan or a.seed or a.refresh or a.verify or a.ingest or "")
    if not root or not os.path.isdir(os.path.join(root, G.SYSTEM_DIR)):
        print("error: pass a project root that contains .sales-system", file=sys.stderr)
        return 2

    if a.plan:
        regs = [a.registry] if a.registry else [
            n for n, s in sorted(G.load_schemas(root).items())
            if any(c["name"] == "crm_id" for c in s["columns"])
            and s.get("browsable", True)]
        for i, reg in enumerate(regs):
            if i:
                print()
            G.sync_query(root, reg)
        return 0

    if not a.registry:
        print("error: --registry is required", file=sys.stderr)
        return 2

    def load_records():
        payload = a.json
        if a.json_file:
            with open(a.json_file, encoding="utf-8") as f:
                payload = f.read()
        if not payload:
            print("error: needs --json-file (or --json)", file=sys.stderr)
            raise SystemExit(2)
        recs = json.loads(payload)
        if isinstance(recs, dict):
            recs = recs.get("records") or recs.get("rows") or recs.get("data") or [recs]
        schema = G.schema_by_registry(root, a.registry)
        fm = G.load_field_map(root)
        d = G.set_dialect(fm)
        fields = ((fm.get("objects", {}) or {}).get(a.registry, {}) or {}).get("fields", {})
        return [G._to_local(r, fields, schema, d) for r in recs]

    if a.verify:
        return G.verify_sync(root, a.registry, load_records(), verbose=a.verbose)

    if a.seed:
        return do_seed(root, a.registry, load_records(), force=a.force)

    if a.refresh:
        return do_refresh(root, a.registry, load_records(), dry_run=a.dry_run,
                          force=a.force)

    if a.ingest:
        schema = G.schema_by_registry(root, a.registry)
        src = a.file
        if not src:
            d = os.path.join(root, os.path.dirname(schema["path"]), "import")
            cands = [os.path.join(d, f) for f in os.listdir(d)
                     if f.lower().endswith((".csv", ".tsv", ".tab"))] \
                if os.path.isdir(d) else []
            if not cands:
                print(f"error: no export given and nothing in {os.path.relpath(d, root)}/",
                      file=sys.stderr)
                return 2
            src = max(cands, key=os.path.getmtime)
            print(f"reading the newest export: "
                  f"{os.path.relpath(src, root)}\n")
        extra = json.loads(a.map) if a.map else None
        r = ingest(root, a.registry, src, extra, key=a.key)

        print(f"{os.path.basename(src)}: {r['rows_read']} data rows, "
              f"{len(r['records'])} usable")
        print(f"  encoding {r['encoding']}, delimiter "
              f"{'tab' if r['delimiter'] == chr(9) else 'comma'}, "
              f"header on line {r['header_row']}")
        print(f"  mapped {len(r['columns_mapped'])} columns: "
              f"{', '.join(r['columns_mapped'][:12])}"
              + (" ..." if len(r["columns_mapped"]) > 12 else ""))
        if r["guessed"]:
            # Say so rather than assuming: a label matched by transformation is a guess,
            # and a wrong guess silently fills a column with the wrong field.
            print(f"  matched by name, worth a glance: {'; '.join(r['guessed'])}")
        if r["footers_dropped"]:
            print(f"  dropped {len(r['footers_dropped'])} footer row(s): "
                  f"{r['footers_dropped'][0]}")
        if r["blank_key"]:
            print(f"  skipped {r['blank_key']} row(s) with no {a.key} — a report without "
                  f"the record ID column can't be matched safely; add it and re-export")
        if r["unmapped"]:
            print(f"  NOT IMPORTED — no mapping for: {', '.join(r['unmapped'][:15])}"
                  + (" ..." if len(r["unmapped"]) > 15 else ""))
            print(f"  If any of those matter, pass --map '{{\"Column Label\": "
                  f"\"local_column\"}}' or save them to "
                  f".sales-system/crm-profile/import-map-{a.registry}.json")

        if a.out:
            with open(a.out, "w", encoding="utf-8") as f:
                json.dump(r["records"], f, indent=1)
            print(f"\nwrote {len(r['records'])} records to {a.out}")
        if a.mode == "records":
            if not a.out:
                json.dump(r["records"], sys.stdout, indent=1)
            return 0
        if not r["records"]:
            print("\nnothing to load.")
            return 1
        print()
        if a.mode == "seed":
            return do_seed(root, a.registry, r["records"], force=a.force,
                           source=os.path.basename(src))
        return do_refresh(root, a.registry, r["records"], dry_run=a.dry_run,
                          force=a.force, source=os.path.basename(src))

    ap.print_help()
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main())
    except G.DestructiveWrite as e:
        print(f"\n{e}\n", file=sys.stderr)
        sys.exit(1)
